name: Deploy To itch.io

on:
  push:
    branches: [ todo ]

jobs:
  deploy_to_itch:
    runs-on: windows-latest
    env:
      NODE_ENV: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.8'
          cache: 'yarn'

      - name: Setup Environment
        run: yarn install
        
      - name: Build and Zip the Game
        run: yarn release

      - name: Butler Push
        run: .\\tools\\butler push dist\\game.zip fanlix/<project-name>:html5 --userversion-file VERSION
        env: 
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
